#!/user/bin/env python
"""Plugin for the `Sphinx`_ documentation engine. Programatically generates
tables describing command-line arguments for `Python`_ modules that use
:class:`~argparse.ArgumentParser` to parse arguments. These tables are then
inserted into descriptions generated by the ``:automodule:`` directive used by
the Sphinx `Autodoc`_ plugin.
"""
from argdoc.ext import setup

__author__ = "Joshua Griffin Dunn"
__date__ = "2015-06-09"
__version__ = "0.0.2"